services:
  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    restart: unless-stopped

  odoo:
    build: .
    # image: odoo:17.0
    depends_on:
      - db
    ports:
      - "8069:8069"
      - "5678:5678"
    volumes:
      - ./config:/etc/odoo
      - ./custom_addons:/mnt/extra-addons 
      - ./filestore:/var/lib/odoo
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
    restart: unless-stopped
    command: python3 -m debugpy --listen 0.0.0.0:5678 /usr/bin/odoo -c /etc/odoo/odoo.conf