services:
  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    restart: unless-stopped

  timescaledb:
    image: timescale/timescaledb:latest-pg15
    environment:
      - POSTGRES_DB=telemetry_db
      - POSTGRES_PASSWORD=default_password
      - POSTGRES_USER=default_user
    volumes:
      - ./timescale_data:/var/lib/postgresql/data
    ports:
      - "5433:5433"
    restart: unless-stopped

  odoo:
    build: .
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - ./config:/etc/odoo
      - ./custom_addons:/mnt/extra-addons 
      - ./filestore:/var/lib/odoo
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
      - TELEMETRY_HOST=timescaledb
      - TELEMETRY_DB=telemetry_db
      - TELEMETRY_USER=default_user
      - TELEMETRY_PASS=default_password
    restart: unless-stopped