services:
  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
    volumes:
      - ./pg_data:/var/lib/postgresql/data
      - ./init_db:/docker-entrypoint-initdb.d
    restart: unless-stopped

  timescaledb:
    image: timescale/timescaledb:latest-pg15
    environment:
      - POSTGRES_DB=telemetry_db
      - POSTGRES_PASSWORD=default_password
      - POSTGRES_USER=default_user
    volumes:
      - ./timescale_data:/var/lib/postgresql/data
    ports:
      - "5433:5433"
    restart: unless-stopped

  odoo:
    build: .
    depends_on:
      - db
      - timescaledb
    ports:
      - "8069:8069"
    volumes:
      - ./config:/etc/odoo
      - ./custom_addons:/mnt/extra-addons 
      - ./filestore:/var/lib/odoo
    environment:
      - HOST=${DB_HOST}
      - PORT=${DB_PORT}
      - USER=${DB_USER}
      - PASSWORD=${DB_PASS}
      - TELEMETRY_HOST=${TELEMETRY_HOST}
      - TELEMETRY_PORT=${TELEMETRY_PORT}
      - TELEMETRY_DB=${TELEMETRY_DB}
      - TELEMETRY_USER=${TELEMETRY_USER}
      - TELEMETRY_PASS=${TELEMETRY_PASS}
    restart: unless-stopped