services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - odoo
    networks:
      - internal_net

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    networks:
      - internal_net

  odoo:
    build: .
    depends_on:
      - odoo_db
      - timescale_db
    volumes:
      - ./config:/etc/odoo
      - ./custom_addons:/mnt/extra-addons 
      - ./filestore:/var/lib/odoo
    environment:
      - HOST=${DB_HOST}
      - PORT=${DB_PORT}
      - USER=${DB_USER}
      - PASSWORD=${DB_PASS}
      - TELEMETRY_HOST=${TELEMETRY_HOST}
      - TELEMETRY_PORT=${TELEMETRY_PORT}
      - TELEMETRY_DB=${TELEMETRY_DB}
      - TELEMETRY_USER=${TELEMETRY_USER}
      - TELEMETRY_PASS=${TELEMETRY_PASS}
    restart: unless-stopped
    networks:
      - internal_net

  odoo_db:
    image: postgres:15
    environment:
      - POSTGRES_DB=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_USER=${DB_USER}
      - TELEMETRY_HOST=${TELEMETRY_HOST}
      - TELEMETRY_PORT=${TELEMETRY_PORT}
      - TELEMETRY_DB=${TELEMETRY_DB}
      - TELEMETRY_USER=${TELEMETRY_USER}
      - TELEMETRY_PASS=${TELEMETRY_PASS}
    volumes:
      - ./pg_data:/var/lib/postgresql/data
      - ./init_db:/docker-entrypoint-initdb.d
    restart: unless-stopped
    networks:
      - internal_net

  timescale_db:
    image: timescale/timescaledb:latest-pg15
    ports:
      - "127.0.0.1:${TELEMETRY_PORT:-5432}:5432"
    environment:
      - POSTGRES_DB=${TELEMETRY_DB}
      - POSTGRES_PASSWORD=${TELEMETRY_PASS}
      - POSTGRES_USER=${TELEMETRY_USER}
    volumes:
      - ./timescale_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - internal_net

  flyway:
    image: flyway/flyway:latest-alpine
    container_name: mes_flyway
    command: 
      - -url=jdbc:postgresql://${TELEMETRY_HOST}:${TELEMETRY_PORT:-5432}/${TELEMETRY_DB}
      - -user=${TELEMETRY_USER}
      - -password=${TELEMETRY_PASS}
      - -baselineOnMigrate=true
      - -baselineVersion=0
      - migrate
    volumes:
      - ./db_migrations:/flyway/sql
    depends_on:
      timescale_db:
        condition: service_started
    networks:
      - internal_net
        
  telemetry_worker:
    build: 
      context: ./twincat_poller
    depends_on:
      - timescale_db
    environment:
      - DB_HOST=${TELEMETRY_HOST}
      - DB_USER=${TELEMETRY_USER}
      - DB_PASS=${TELEMETRY_PASS}
      - DB_NAME=${TELEMETRY_DB}
    networks:
      - internal_net

volumes:
  odoo_web_data:
  odoo_db_data:
  timescale_data:

networks:
  internal_net:
    driver: bridge